tensor_dataset:
  folder: "/Users/zetasourpi/Desktop/GitRepoQC/AIQualityControl/data-ingestion/good_run_tpc_qual/tensor"
  limit: 200
  add_channel: True 
  log1p: False
  normalize: None

dataset:
  folder: "/Users/zetasourpi/cernbox/data/data-for-ml/good_quality_cluster_data/rgb_images"
  limit: ~

data_split:  
  train_split: 0.8
  split_seed: 42

dataloader_args:
  batch_size: 16
  shuffle: true
  num_workers: 0
  pin_memory: false

linear_model_parametrs:
  latent_dim: 64
  hidden_dim: 500
  channels: 3

convolutional_model_parameters: 
  in_channels: 3
  base_channels: 96

  conv:
      kernel_size: 3
      stride: 2
      padding: 1

  deconv:
      kernel_size: 3
      stride: 2
      padding: 1
      out_pads: [1, 0, 0, 1]

train:
  epochs: 30
  lr: 1e-4
  seed: 123

viz:
  every_n_epochs: 4
  threshold: 0.05
  num_samples: 4
  loss_map_cmap: "jet"


mlflow:
  run_name: "increase_base_channels_to_96"                     
  experiment_name: "exp_010_updated_data_convAE"
  tracking:
    backend: "sqlite"                 
    local_uri: "sqlite:////Users/zetasourpi/cernbox/mlflow-backend/mlflow.db"               
    artifact_root: "/Users/zetasourpi/cernbox/mlflow-backend/mlruns"   # Always used from the server side (so mlflow ui)
    server_uri: "http://127.0.0.1:8080"
  tags:
    project: "ai-qc"
    model_type: "ConvAE"
    change: "None"
    dataset: "Good Quality TPC Cluster Maps (Images)"
  detailed_comments: "None"
  detailed_comments_filename: "notes.md"

